### PR TITLE
chore(breaking): add EIGENDA_PROXY prefix to memstore flags

### PR DESCRIPTION
**Pull request by samlaf**
Needed for consistency with all other flags. For some reason MEMSTORE flags are the only ones without the EIGENDA_PROXY flag.
image

## Breaking
This is a breaking change for anyone who was running the proxy using the env var flags. They will need to add the prefix so we should communicate this change.

### CODE REVIEW

**Review by hopeyen — COMMENTED** [review]
would you be able to also update the .env.example files? like https://github.com/Layr-Labs/eigenda-proxy/blob/ae7a0da530ec89a8432f3d3d6d65af95da46ee02/.env.example.holesky#L65

**Comment by bxue-l2** [comment]
We can make it non-breaking by having both ENV available.

**Comment by samlaf** [comment]
> bfe39a6

Done: [bfe39a6](https://github.com/Layr-Labs/eigenda-proxy/pull/121/commits/bfe39a6d132a5343913cb97b809d98b8ea127e3f)

**Review by epociask — APPROVED** [review]
LGTM - breaking the env namespace should be fine given customers should never use them in a production setting

**Comment by bxue-l2** [comment]
> LGTM - breaking the env namespace should be fine given customers should never use them in a production setting

good point

**Pull request merged**
